version: "3"

services:
  pgdb:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "portfolio"
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgres/data/
